repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt      # Ensures consistent spacing/indentation
      - id: terraform_validate  # Basic syntax & schema validation
      - id: terraform_tflint   # Catches AWS provider-specific errors
        args:
          - "--args=--config=.tflint.hcl"
      - id: terraform_docs      # Automates Technical Reference updates
        args:
          - --args=--prefix=README.template.md

  - repo: local
    hooks:
      - id: checkov
        name: Checkov
        description: Runs checkov on Terraform files.
        entry: python -m checkov.main # Set for my path
        language: system
        pass_filenames: false
        always_run: true
        args: ["--directory", "."]
