repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt      # Ensures consistent spacing/indentation
      - id: terraform_validate  # Basic syntax & schema validation
      - id: terraform_tflint   # Catches AWS provider-specific errors
        args:
          - "--args=--config=.tflint.hcl"
      - id: terraform_docs      # Automates Technical Reference updates
        args:
          - --args=--prefix=README.template.md
      - id: terraform_checkov   # Enforces the security policies in .checkov.yml
        args:
          - "--args=--config-file .checkov.yml"
