# This file suppresses specific security checks globally.

exclude:
  # Disables: S3 Bucket does not have logging enabled
  - aws-s3-enable-bucket-logging
  
  # Disables: S3 Data should be versioned 
  # (Note: Use this if you want to silence the warning even where versioning is missing)
  - aws-s3-enable-versioning

  # Disables: CloudWatch log groups should be encrypted using CMK
  - aws-cloudwatch-log-group-customer-key